LIBNAME OUT 'C:\Projetos\RMs Proc. 03605.001726-2014-52 - FJP Maria Luiza Marques\Maceio\Habitacao\2000\Agregacoes';
LIBNAME IN 'C:\Projetos\Projeto Proc. 03605.001349-2012-90 - FJP Maria Luiza Marques\Programas\Habitacao\2000';

 OPTIONS PS=10000 NODATE LS=250 OBS=MAX;


DATA SETOR;
SET IN.habit00;


UF=SUBSTR(SETORC,1,2);
IF UF='27';*AL;


IF POP=. THEN POP=0;
IF AGUA_ESGOTO=. THEN AGUA_ESGOTO=0;
IF AGUA=. THEN AGUA=0;
IF BANAGUA=. THEN BANAGUA=0;
IF LIXO=. THEN LIXO=0;
IF LUZ=. THEN LUZ=0;
IF DENS=. THEN DENS=0;
IF POPURB=. THEN POPURB=0;




/* IMPORTACAO DO ARQUIVO CONTENDO O DIVISOR  */
PROC IMPORT OUT= WORK.DIV_A
            DATAFILE= "C:\Projetos\RMs Proc. 03605.001726-2014-52 - FJP Maria Luiza Marques\Base_mae\Maceio\DIV_mun00.txt"
            DBMS=TAB REPLACE;
     GETNAMES=YES;
     DATAROW=2;
RUN;


/* IMPORTACAO DO ARQUIVO CONTENDO BASE MAE */
PROC IMPORT OUT= WORK.MAE_A
            DATAFILE= "C:\Projetos\RMs Proc. 03605.001726-2014-52 - FJP Maria Luiza Marques\Base_mae\Maceio\MAE_mun00.txt"
            DBMS=TAB REPLACE;
     GETNAMES=YES;
     DATAROW=2;
RUN;




DATA MAE_A(KEEP=SETORC MUN10);
SET MAE_A;


setor=PUT(Setor_2000,15.);
set1=substr(Setor,1,6);
set11=put(set1,6.);
set2=substr(Setor,8,8);
set22=put(set2,8.);
SETORC=set11!!set22;



MUN10=Cod_Mun10_2000;



PROC SORT DATA=MAE_A;
BY SETORC;



DATA DIV_A (KEEP=SETORC DIVPESO);
SET DIV_A;


setor=PUT(Setor_2000,15.);
set1=substr(Setor,1,6);
set11=put(set1,6.);
set2=substr(Setor,8,8);
set22=put(set2,8.);
SETORC=set11!!set22;



DIVPESO=Div_Mun10_00;


PROC SORT DATA=DIV_A;
BY SETORC;


DATA DIVMAE;
MERGE MAE_A(IN=A) DIV_A(IN=B);
IF A AND B;
BY SETORC;run;


DATA DIVMAE(DROP= DIVPESO);
SET DIVMAE;

RETAIN D(0);
 IF FIRST.SETORC THEN DO;
  D=0;
 BY SETORC;
END;

D=D+1;


DATA UMO;
MERGE SETOR(IN=A) DIV_A(IN=B);
IF A;
BY SETORC;

IF DIVPESO=1;

D=1;

DATA DEDOS;
MERGE SETOR(IN=A) DIV_A(IN=B);
IF A;
BY SETORC;

IF DIVPESO=2;

DATA DEDOS;
SET DEDOS DEDOS;

PROC SORT DATA=DEDOS;
BY SETORC;

DATA DEDOS;
SET DEDOS;

RETAIN D(0);
  IF FIRST.SETORC THEN DO;
  D=0;
  BY SETORC;
END;

D=D+1;


DATA DETRE;
MERGE SETOR(IN=A) DIV_A(IN=B);
IF A;
BY SETORC;

IF DIVPESO=3;

DATA DETRE;
SET DETRE DETRE DETRE;

PROC SORT DATA=DETRE;
BY SETORC ;

DATA DETRE;
SET DETRE;

RETAIN D(0);
  IF FIRST.SETORC THEN DO;
  D=0;
  BY SETORC ;
END;

D=D+1;

DATA DECUA;
MERGE SETOR(IN=A) DIV_A(IN=B);
IF A;
BY SETORC;

IF DIVPESO=4;

DATA DECUA;
SET DECUA DECUA DECUA DECUA;

PROC SORT DATA=DECUA;
BY SETORC ;

DATA DECUA;
SET DECUA;

RETAIN D(0);
  IF FIRST.SETORC THEN DO;
  D=0;
  BY SETORC ;
END;

D=D+1;


DATA DECIN;
MERGE SETOR(IN=A) DIV_A(IN=B);
IF A;
BY SETORC;

IF DIVPESO=5;

DATA DECIN;
SET DECIN DECIN DECIN DECIN DECIN;

PROC SORT DATA=DECIN;
BY SETORC ;

DATA DECIN;
SET DECIN;

RETAIN D(0);
  IF FIRST.SETORC THEN DO;
  D=0;
  BY SETORC ;
END;

D=D+1;


DATA DESEI;
MERGE SETOR(IN=A) DIV_A(IN=B);
IF A;
BY SETORC;

IF DIVPESO=6;

DATA DESEI;
SET DESEI DESEI DESEI DESEI DESEI DESEI;

PROC SORT DATA=DESEI;
BY SETORC ;

DATA DESEI;
SET DESEI;

RETAIN D(0);
  IF FIRST.SETORC THEN DO;
  D=0;
  BY SETORC ;
END;

D=D+1;




DATA SETOR;
SET UMO DEDOS DETRE DECUA DECIN DESEI;


PROC SORT DATA=SETOR;
BY SETORC D;

PROC SORT DATA=DIVMAE;
BY SETORC D;


DATA JUNTO;
MERGE SETOR(IN=A) DIVMAE(IN=B);
IF A AND B;
BY SETORC D;


PROC MEANS DATA=JUNTO SUM;
VAR POP POPURB;



DATA JUNTO(DROP=POP POPURB AGUA_ESGOTO AGUA BANAGUA LIXO LUZ DENS);
SET JUNTO;


DPOP=POP/DIVPESO;
DPOPURB=POPURB/DIVPESO;

DAGUA_ESGOTO=AGUA_ESGOTO/DIVPESO;
DAGUA=AGUA/DIVPESO;
DBANAGUA=BANAGUA/DIVPESO;
DLIXO=LIXO/DIVPESO;
DLUZ=LUZ/DIVPESO;
DDENS=DENS/DIVPESO;


PROC MEANS DATA=JUNTO SUM;
VAR DPOP DPOPURB;


******************************** CALCULANDO OS INDICADORES - MUN10 ********************************;

DATA FIM(DROP=DPOP DPOPURB DAGUA_ESGOTO DAGUA DBANAGUA DLIXO DLUZ DDENS);
 SET JUNTO;


POP=DPOP;
POPURB=DPOPURB;

AGUA_ESGOTO=DAGUA_ESGOTO;
AGUA=DAGUA;
BANAGUA=DBANAGUA;
LIXO=DLIXO;
LUZ=DLUZ;
DENS=DDENS;



PROC SORT DATA=FIM;
BY Mun10;



PROC MEANS DATA=FIM SUM NOPRINT;
VAR POP POPURB AGUA_ESGOTO AGUA BANAGUA LIXO LUZ DENS;
OUTPUT OUT=SOMA1 (KEEP=Mun10 POP POPURB AGUA_ESGOTO AGUA BANAGUA LIXO LUZ DENS)
       SUM=POP POPURB AGUA_ESGOTO AGUA BANAGUA LIXO LUZ DENS;
BY Mun10;



DATA FIM(KEEP=Mun10 T_AGUA T_BANAGUA T_AGUA_ESGOTO T_LIXO T_LUZ T_DENS);
SET SOMA1;


*** HABITACAO ***;


IF POP>0 THEN T_AGUA=(AGUA/POP)*100;
ELSE          T_AGUA=0;

IF POP>0 THEN T_BANAGUA=(BANAGUA/POP)*100;
ELSE          T_BANAGUA=0;

IF POP>0 THEN T_AGUA_ESGOTO=(AGUA_ESGOTO/POP)*100;
ELSE          T_AGUA_ESGOTO=0;

IF POPURB>0 THEN T_LIXO=(LIXO/POPURB)*100;
ELSE             T_LIXO=0;

IF POP>0 THEN T_LUZ=(LUZ/POP)*100;
ELSE          T_LUZ=0;

IF POP>0 THEN T_DENS=(DENS/POP)*100;
ELSE          T_DENS=0;


*** GRAVACAO ***;

DATA OUT.HABIT00_Mun10;
SET FIM;


************************************;
*** IMPORTANDO A BASE PARA EXCEL ***;
************************************;

PROC DBLOAD DBMS=EXCEL DATA= OUT.HABIT00_Mun10;
PATH='C:\Projetos\RMs Proc. 03605.001726-2014-52 - FJP Maria Luiza Marques\Maceio\Habitacao\2000\Agregacoes\HABIT00_Mun10.XLS';
PUTNAMES=YES;
LIMIT=0;
LOAD;




RUN;
